version: "3"
services:
  database:
    image: postgres:alpine
    container_name: "vote_database"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "vote_database"
      POSTGRES_USER: "vote_user"
      POSTGRES_PASSWORD: "siosdhf8972903bnjasd81jk"
