### Get Posts
GET http://127.0.0.1:8000/post
Content-Type: application/json

### Get Post By id
GET http://127.0.0.1:8000/post/1
Content-Type: application/json

### Get Users
GET http://127.0.0.1:8000/user
Content-Type: application/json

### Get User By id
GET http://127.0.0.1:8000/user/1
Content-Type: application/json

### Add Post
POST http://127.0.0.1:8000/post
Content-Type: application/json

{
  "name": "Kosun lastest post",
  "userId": 3
}

### Add User
POST http://127.0.0.1:8000/user
Content-Type: application/json

{
  "name": "Kosun"
}

### Test
GET http://127.0.0.1:8000/